name: dwallet
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.17.1 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  dio: ^4.0.6
  get_storage: ^2.0.3
  flutter_svg: ^1.1.0
  page_view_indicators: ^2.0.0
  device_preview: ^1.1.0
  flutter_spinkit: ^5.1.0

#  web3
  build: ^2.0.0
  build_config: ^1.0.0
  dart_style: ^2.0.0
  code_builder: ^4.0.0
  path: ^1.8.0
  built_collection: ^5.0.0
  pointycastle: ^3.4.0
  convert: ^3.0.0
  meta: ^1.1.0
  http: ^0.13.0
  js: ^0.6.3
  uuid: ^3.0.1
  typed_data: ^1.1.6
  stream_channel: ^2.0.0
  stream_transform: ^2.0.0
  json_rpc_2: ^3.0.0
  collection: ^1.14.11
  bip39: ^1.0.6
  bip32: ^2.0.0
  encrypt: ^5.0.1
  fluttertoast: ^8.0.9
  liquid_pull_to_refresh: ^3.0.1
  syncfusion_flutter_charts: ^20.1.61
  searchable_listview: ^1.6.0
  quantity: ^2.0.0
  intl: ^0.17.0
  animated_text_kit: ^4.2.2
  qr_flutter: ^4.0.0
  share_plus: ^4.0.10+1
  url_launcher: ^6.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/icons/
    - assets/files/
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
        - asset: assets/fonts/OpenSans-Medium.ttf
        - asset: assets/fonts/OpenSans-Regular.ttf